package com.example.appembalaje.interfaces;

public interface DAO {

    String DATABASE="aislapp.db";
    String CREATE_DATABASE_QUERY="";
    String CREATE_TABLE_EMPLEADOS_QUERY="CREATE TABLE Empleados (rut INTEGER PRIMARY KEY, nombre TEXT";
    String CREATE_TABLE_COTIZACION_QUERY="CREATE TABLE Cotizacion(IDCotizacion INTEGER PRIMARY KEY)";
    String CREATE_TABLE_PRODUCTOS_QUERY="CREATE TABLE Productos()";
    String CREATE_TABLE_CATEGORIA_QUERY="CREATE TABLE Categoria()";
    String CREATE_TABLE_SUBCATEGORIA_QUERY="CREATE TABLE Subcategoria()";
    String CREATE_TABLE_VENTA_QUERY="CREATE TABLE Venta()";
    String DELETE_TABLE_CATEGORIA_QUERY="DROP TABLE IF EXIST Categoria";
    String DELETE_TABLE_COTIZACION_QUERY="DROP TABLE IF EXIST Cotizacion";
    String DELETE_TABLE_PRODUCTOS_QUERY="DROP TABLE IF EXIST Productos";
    String DELETE_TABLE_SUBCATEGORIA_QUERY="DROP TABLE IF EXIST Subcategoria";
    String DELETE_TABLE_VENTA_QUERY="DROP TABLE IF EXIST Subcategoria";

}
